### ISSUE TITLE
DeleteObjet:  AttributeError: 'str' object has no attribute 'toxml'

### ISSUE THREAD

**Issue by Athius** [minio/minio-py#1108]
I try to delete some objects using the remove_objects function.

I create a small class encapsulating minio.Minio.

The following code works (I have the good credentials, and the files created are removed):
```python
# self.storage is my class that calls list_objects
# self.storage.client is minio.Minio
delete_object_list = map(
    lambda x: DeleteObject(x.object_name), self.storage.list_objects(self.bucket_name, recursive=True),)
errors = self.storage.client.remove_objects(self.bucket_name, delete_object_list)
for error in errors:
    print("error occured when deleting object", error)
```

Now, I create a function encapsulating remove_objects function:

```python
def remove_objects(self, bucket_name: str, object_list: Iterable[str]) -> Union[Generator[DeleteError, None, None], Generator[Any, None, None]]:
    delete_object_list = map(lambda x: DeleteObject(x), object_list)
    return self.client.remove_objects(bucket_name, delete_object_list)
```

The following code returns *AttributeError: 'str' object has no attribute 'toxml'* when I run it on my unit tests (using unittest framework)

If launch the test in debug mode, I don't have any error.

The following code describe the test done:

```python
def test_remove_objects(self):
    data = BytesIO("string".encode("utf-8"))
    self.storage.put_object(self.bucket_name, "test", data, len(data.getbuffer()))
    data = BytesIO("string".encode("utf-8"))
    self.storage.put_object(self.bucket_name, "test2", data, len(data.getbuffer()))
    self.assertTrue(len(list(self.storage.list_objects(self.bucket_name))) == 2)
    object_list = ["test", "test2"]
    errors = self.storage.remove_objects(self.bucket_name, object_list)
    self.assertTrue(len(list(errors)) == 0)
    self.assertTrue(len(list(self.storage.list_objects(self.bucket_name))) == 0)
```
(The bucket is already created, and the files are correctly created too)

I'm on Windows 10, python 3.7.9 and minio in 7.0.3.

Does anyone have some ideas of this weird behavior?

Thanks

**Comment by balamurugana** [comment]
In your `remove_object()`, examine `object_list` arg values and `delete_object_list` values.

**Comment by Athius** [comment]
Another problem due to the guy between the keyboard and the chair: the mistake was the version of the code I used (it was installed with a bad version).

**Comment by god-chaos** [comment]
maybe this is bug. remove_objects method is work in 6.0.2, but it's not work in 7.0.x

**Comment by god-chaos** [comment]
maybe this is bug. remove_objects method is work in 6.0.2, but it's not work in 7.0.x

> Another problem due to the guy between the keyboard and the chair: the mistake was the version of the code I used (it was installed with a bad version).
